apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 483106397391.dkr.ecr.ap-northeast-2.amazonaws.com/njnt-tomcat:7
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-njnt-secret